#!/usr/bin/env python
""" usage: check_geiger [options]

Options:
    -w --warning <hours>            Warning threshold for hours since last data entry [default: 24]
    -c --critical <hours>           Warning threshold for hours since last data entry [default: 72]
    -h --hostid <id>                Host Identity in radioactiveathome [default: 14364]
    -u --url <URL>                  radioactivehome trickledata [default: http://radioactiveathome.org/boinc/gettrickledata.php]

first=$(curl -s http://radioactiveathome.org/boinc/gettrickledata.php?hostid=14364| head -n 1 | cut -d: -f 2 )

last_date=$(curl  -s "http://radioactiveathome.org/boinc/gettrickledata.php?hostid=14364&start=$(($first-1))" \
  | tail -n 1 |  cut -d, -f4)
date_ts=$(date -d"$last_date" +%s )
date_now=$(date +%s)

echo "Seconds since last data:" $(($date_now -  $date_ts))
if test  $(($date_now -  $date_ts < 60*60*24)) -eq '0' ;then
"""


from docopt import docopt
import requests,csv,sys
from datetime import datetime,timedelta

if __name__ == "__main__":
    args = docopt(__doc__)
    warn = timedelta(hours=int(args['--warning']))
    crit = timedelta(hours=int(args['--critical']))
    hostid = args['--hostid']
    url = args['--url']
    payload = {'hostid':hostid}
    try:
        ret = requests.get(url,params=payload)
        current_data_field = int(ret.text.split('\n')[0].split(':')[1])
        payload['start'] =current_data_field -1
        current_data = requests.get(url,params=payload).text.split('\n')[-2].split(',')
    except:
        print("radiation UNKNOWN - cannot retrieve data from {}".format(url))
        sys.exit(3)
    try:

        timeout = datetime.now() - datetime.strptime(current_data[3],"%Y-%m-%d %H:%M:%S")
        if timeout > crit:
            print("radiation timeout CRITICAL  - no data since {} hours ".format((timeout.seconds /60) /60))
            sys.exit(2)
        elif timeout > warn:
            print("radiation timeout WARNING - no data since {} hours ".format((timeout.seconds /60) /60))
            sys.exit(1)
        else:
            print("radiation timeout OK - last data {} minutes ago".format((timeout.seconds /60) ))
            sys.exit(0)
    except Exception as e:
        print("radiation UNKNOWN - cannot calculate data from input - {}".format(e))
        sys.exit(3)
